### ISSUE TITLE
Cannot encode ActiveSupport::TimeWithZone

### ISSUE THREAD

**Issue by janraasch** [getsentry/raven-ruby#280]
Hi guys, we encoutered this after our recent update to `v0.12.2` (from `v0.10.1`). Stack trace:

```bash
cannot encode ActiveSupport::TimeWithZone: Thu, 08 Jan 2015 05:38:50 CET +01:00
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:84:in `valenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `block in objenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `map'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `objenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:75:in `valenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `block in objenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `map'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `objenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:75:in `valenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `block in objenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `map'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:438:in `objenc'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/okjson.rb:65:in `encode'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/client.rb:57:in `encode'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/client.rb:34:in `send'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/base.rb:71:in `send'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/base.rb:109:in `block in capture_exception'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/base.rb:136:in `send_or_skip'
/app/vendor/bundle/ruby/2.1.0/gems/sentry-raven-0.12.2/lib/raven/base.rb:103:in `capture_exception'
...
```

This may be related to https://github.com/getsentry/raven-ruby/issues/276. Switching back to `v0.10.1` would solve the issue, but we would really like to get to `v0.12.2` for security reasons.

**Comment by nateberkopec** [comment]
Fixed by #249. Please upgrade to 0.12.3 and let me know if it works for you.
