### ISSUE TITLE
NameError: undefined local variable or method `exception' for Raven::Rack:Class

### ISSUE THREAD

**Issue by poiati** [getsentry/raven-ruby#289]
Hello guys,

I'm getting the error bellow in all environments. No exceptions are caught with Raven, only for RAKE tasks.

Here is my setup:

```
config.consider_all_requests_local = false
config.action_dispatch.show_exceptions = true
```

```
require 'raven'

Raven.configure do |config|
  config.dsn = 'https://#@app.getsentry.com/#'
end
```

```
use Raven::Rack
use ActionDispatch::Static
use Rack::Lock
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use ActionDispatch::Head
use Rack::ConditionalGet
use Rack::ETag
use ActionDispatch::BestStandardsSupport
use Warden::Manager
use ServeGridfsImage
use Rack::Mongoid::Middleware::IdentityMap
use RequestStore::Middleware
use OmniAuth::Strategies::Facebook
run Godoc::Application.routes
```

Using Raven 0.12.3

```
[2015-01-19 14:00:30] ERROR NameError: undefined local variable or method `exception' for Raven::Rack:Class
        /Users/poiati/.rvm/gems/ruby-1.9.3-p448@boaconsulta/bundler/gems/raven-ruby-40b7d4c23e24/lib/raven/integration
s/rack.rb:29:in `capture_type'
        /Users/poiati/.rvm/gems/ruby-1.9.3-p448@boaconsulta/bundler/gems/raven-ruby-40b7d4c23e24/lib/raven/integration
s/rack.rb:59:in `rescue in call'
        /Users/poiati/.rvm/gems/ruby-1.9.3-p448@boaconsulta/bundler/gems/raven-ruby-40b7d4c23e24/lib/raven/integration
s/rack.rb:53:in `call'
        /Users/poiati/.rvm/gems/ruby-1.9.3-p448@boaconsulta/gems/railties-3.2.18/lib/rails/engine.rb:484:in `call'
        /Users/poiati/.rvm/gems/ruby-1.9.3-p448@boaconsulta/gems/railties-3.2.18/lib/rails/application.rb:231:in `call
'
        /Users/poiati/.rvm/gems/ruby-1.9.3-p448@boaconsulta/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
        /Users/poiati/.rvm/gems/ruby-1.9.3-p448@boaconsulta/gems/railties-3.2.18/lib/rails/rack/log_tailer.rb:17:in `c
all'
        /Users/poiati/.rvm/gems/ruby-1.9.3-p448@boaconsulta/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service
'
        /Users/poiati/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
        /Users/poiati/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
        /Users/poiati/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

Tks in advance!

**Comment by nateberkopec** [comment]
Are you using our github repository as your gem source?

**Comment by poiati** [comment]
Yes I am. 

```
gem "sentry-raven", :git => "https://github.com/getsentry/raven-ruby.git"
```

**Comment by poiati** [comment]
Also relevant: I'm using Rails 3.2.21.

**Comment by poiati** [comment]
I believe the problem is in an argument name missmatch:

https://github.com/getsentry/raven-ruby/commit/fd957d6c1f884fa9857ae0bbc22fd5187389693a

The argument is named `message` not `exception`.

**Comment by poiati** [comment]
PR open: https://github.com/getsentry/raven-ruby/pull/290

**Comment by nateberkopec** [comment]
Thanks. I'm going to leave this issue open until we get test coverage around that, it's pretty bad that this didn't break a build.

**Comment by nateberkopec** [comment]
Part of the problem here is that `rack_spec.rb` is over-mocking and not actually testing anything in the Rack integration.

**Comment by nateberkopec** [comment]
This is now covered by the integration testing in the Rails spec.
