### ISSUE TITLE
Issues with ActiveJob (+Sidekiq) reporting errors in jobs with serialized records

### ISSUE THREAD

**Issue by lleger** [getsentry/raven-ruby#384]
I'm having issues with Raven reporting errors that happen inside of ActiveJob jobs when Raven is configured to send events in the background. When a job runs that triggers an exception, the background Raven job fires and eventually dies with this message:

> ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
> ERROR: Can't serialize a Hash with reserved key "_aj_globalid"
> ERROR: [edit]/activejob-4.2.4/lib/active_job/arguments.rb:126:in `serialize_hash_key'

I successfully reproduced this issues consistently in [this test repository I created](https://github.com/lleger/testsentrybg). It's a vanilla Rails 4.2.4 app, and all of the gems are up-to-date. I then added Raven and configured it to report in development and to report via background job. I also added Sidekiq. To exhibit the issue, perform the following steps:

1. Clone the repo
2. Migrate and seed the database
3. Boot Sidekiq: `bundle exec sidekiq`
4. Open up Rails console and run:
  - `ExceptionJob.perform_later` — successfully reports to Sentry
  - `ExceptionJob.perform_later([])` — successfully reports to Sentry
  - `ExceptionJob.perform_later(Post.first)` — failure

My assumption is that it fails because of the ActiveJob serialization. When the Sentry reporter job gets run, it serializes a hash that includes the parameters sent to ActiveJob. You can see in [ActiveJob's source](https://github.com/rails/rails/blob/d5890bdf660f670271a8f60bd091bd11db4c23b3/activejob/lib/active_job/arguments.rb#L123-L127) that they have a `RESERVED_KEYS` hash. Since the parameters sent to ActiveJob would contain a hash that has these keys, it would make sense that that is causing the issue.

I also tested this against the ActiveJob inline adapter, but it didn't seem to have the same issues. I only tested it against Sidekiq, which is what I was using when I noticed the issue.

**Comment by mattrobenolt** [comment]
Hey @lleger, just wanted to follow up and let you know that I'm going to be diving into this this week.

I'm not familiar with Rails or Sidekick personally, so I highly appreciate the steps to reproduce.

I'll report back with findings. :)

**Comment by lleger** [comment]
Thanks for the update. Happy to help diagnose if I can. I only tried with Sidekiq, but I would think the problem would exhibit itself in any of the adapters that serialize to a data store.

**Comment by mattrobenolt** [comment]
Alright, I've reproduced the bug. :)

```
2015-11-06T21:24:55.360Z 31 TID-ovl819mrw ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2015-11-06T21:24:55.360Z 31 TID-ovl819mrw ERROR: Can't serialize a Hash with reserved key "_aj_globalid"
2015-11-06T21:24:55.361Z 31 TID-ovl819mrw ERROR: /usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:126:in `serialize_hash_key'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:102:in `block in serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each_with_object'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:65:in `serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:58:in `block in serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:58:in `map'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:58:in `serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:102:in `block in serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each_with_object'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:65:in `serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:58:in `block in serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:58:in `map'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:58:in `serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:102:in `block in serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each_with_object'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:65:in `serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:102:in `block in serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each_with_object'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:65:in `serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:102:in `block in serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `each_with_object'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:101:in `serialize_hash'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:65:in `serialize_argument'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:33:in `block in serialize'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:33:in `map'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/arguments.rb:33:in `serialize'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/core.rb:86:in `serialize_arguments'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/core.rb:72:in `serialize'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:25:in `enqueue'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/enqueuing.rb:71:in `block in enqueue'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/logging.rb:14:in `call'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/logging.rb:14:in `block (3 levels) in <module:Logging>'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `block in tag_logger'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `tag_logger'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/logging.rb:13:in `block (2 levels) in <module:Logging>'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_enqueue_callbacks'
/usr/local/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/enqueuing.rb:67:in `enqueue'
/usr/local/bundle/gems/activejob-4.2.4/lib/active_job/enqueuing.rb:17:in `perform_later'
/usr/src/app/config/initializers/sentry.rb:6:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sentry-raven-0.15.2/lib/raven/base.rb:122:in `call'
/usr/local/bundle/gems/sentry-raven-0.15.2/lib/raven/base.rb:122:in `capture_type'
/usr/local/bundle/gems/sentry-raven-0.15.2/lib/raven/integrations/sidekiq.rb:26:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq/exception_handler.rb:20:in `call'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq/exception_handler.rb:20:in `block in handle_exception'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq/exception_handler.rb:18:in `each'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq/exception_handler.rb:18:in `handle_exception'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq/processor.rb:66:in `rescue in process'
/usr/local/bundle/gems/sidekiq-3.5.3/lib/sidekiq/processor.rb:70:in `process'
/usr/local/bundle/gems/celluloid-0.17.2/lib/celluloid/calls.rb:28:in `public_send'
/usr/local/bundle/gems/celluloid-0.17.2/lib/celluloid/calls.rb:28:in `dispatch'
/usr/local/bundle/gems/celluloid-0.17.2/lib/celluloid/call/async.rb:7:in `dispatch'
/usr/local/bundle/gems/celluloid-0.17.2/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/local/bundle/gems/celluloid-0.17.2/lib/celluloid/cell.rb:76:in `block in task'
/usr/local/bundle/gems/celluloid-0.17.2/lib/celluloid/actor.rb:339:in `block in task'
/usr/local/bundle/gems/celluloid-0.17.2/lib/celluloid/task.rb:44:in `block in initialize'
/usr/local/bundle/gems/celluloid-0.17.2/lib/celluloid/task/fibered.rb:14:in `block in create'
2015-11-06T21:24:56.797Z 31 TID-ovl7ww9v8 ReportSentryJob JID-6da6e7ef4242067ab531e516 INFO: done: 2.654 sec
```

Now I can try to debug this and see what's going on. Thanks again, this repository has been super useful.

**Comment by lleger** [comment]
:clap:
