### ISSUE TITLE
NoMethodError: undefined method `has_key?' for nil:NilClass after adding Raven-ruby to app

### ISSUE THREAD

**Issue by lubekpl** [getsentry/raven-ruby#473]
Hi guys!

I'm using ruby 1.8.7-p374 with a Rails 3 app. I've added raven-ruby (0.15.5) to the project and after an error occurs (the original one), the original error is covered up by
`ERROR NoMethodError: undefined method 'has_key?' for nil:NilClass`. 

Here's the backtrace:

```ruby
[2016-02-26 11:43:08] ERROR NoMethodError: undefined method `has_key?' for nil:NilClass
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/rack-1.3.8/lib/rack/runtime.rb:20:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/activesupport-3.1.10/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/rack-1.3.8/lib/rack/lock.rb:15:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/actionpack-3.1.10/lib/action_dispatch/middleware/static.rb:61:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/bundler/gems/raven-ruby-00974f3685c4/lib/raven/integrations/rack.rb:53:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/railties-3.1.10/lib/rails/engine.rb:456:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/railties-3.1.10/lib/rails/application.rb:143:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/rack-1.3.8/lib/rack/content_length.rb:14:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/railties-3.1.10/lib/rails/rack/log_tailer.rb:14:in `call'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/rack-1.3.8/lib/rack/handler/webrick.rb:59:in `service'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /Users/user_name/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:82:in `start'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/rack-1.3.8/lib/rack/handler/webrick.rb:13:in `run'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/rack-1.3.8/lib/rack/server.rb:268:in `start'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/railties-3.1.10/lib/rails/commands/server.rb:70:in `start'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/railties-3.1.10/lib/rails/commands.rb:54
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/railties-3.1.10/lib/rails/commands.rb:49:in `tap'
  /Users/user_name/.rvm/gems/ruby-1.8.7-p374@gemset/gems/railties-3.1.10/lib/rails/commands.rb:49
  script/rails:6:in `require'
  script/rails:6
```

Another thing is that Sentry gets info about two errors, the first one (original one) and the "cover up" error. This is quite annoying but the real issue is that the end user sees a blank page if an error occurs rather than an error page. 

Found [this](http://stackoverflow.com/questions/16100978/i-get-undefined-method-has-key-for-nilnilclass-for-all-errors) but the solution (whiny nils) doesn't work. 

As soon as I remove raven-ruby this odd behaviour stops and the original errors appear again

I'm quite aware that the new release dropped support for 1.8.7 (hance, using 0.15.5 :smile:) but if you could point me to a possible solution I'd greatly appreciate it.

**Comment by nateberkopec** [comment]
Hm. I have no idea what's happening here - you're on your own.

It's weird that removing raven-ruby fixes this for you, because that error appears to originate in the Rack::Runtime middleware.
