### ISSUE TITLE
NoMethodError undefined method `backtrace' for Raven::Event

### ISSUE THREAD

**Issue by will** [getsentry/raven-ruby#476]
I'm just starting with sentry and trying to figure out how to use the docs method of async reporting, but having problems.

using `sentry-raven-0.15.6`

configured like 
```
class SentryJob
  include SuckerPunch::Job

  def perform(event)
    Raven.send_event(event)
  end
end

Raven.configure do |config|
  config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s)
  config.environments = ['production']
  config.async = lambda { |event|
    SentryJob.perform_async(event)
  }
end
```

```
irb(main):003:0> Raven.capture { 1/0}
ZeroDivisionError: Sucker Punch job error for class: 'SentryJob' args: [#<Raven::Event:0x007ff2014b3ed0, {}, {}, {}]
NoMethodError undefined method `backtrace' for #<Raven::Event:0x007ff2014b3ed0>
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:189:in `block (3 levels) in add_exception_interface'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/interfaces.rb:12:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:183:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:183:in `block (2 levels) in add_exception_interface'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:182:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:182:in `block in add_exception_interface'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/interfaces.rb:12:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:86:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:86:in `interface'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:168:in `add_exception_interface'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:144:in `block in from_exception'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:52:in `initialize'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:139:in `new'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/event.rb:139:in `from_exception'
/app/vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/base.rb:113:in `capture_type'
/app/config/initializers/sentry.rb:8:in `perform'
/app/vendor/bundle/ruby/2.3.0/gems/sucker_punch-2.0.1/lib/sucker_punch/job.rb:57:in `__run_perform'
/app/vendor/bundle/ruby/2.3.0/gems/sucker_punch-2.0.1/lib/sucker_punch/job.rb:36:in `block in perform_async'
/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by nateberkopec** [comment]
@will can you upgrade to 1.20.0 and tell me if this problem still exists for you?

**Comment by will** [comment]
1.2.0 looks good. I'm not using suckerpunch anymore but `  config.async = ->(e) { Concurrent::Future.execute { Raven.send_event(e) } }` seems to be working
