### ISSUE TITLE
Rack Timeout support

### ISSUE THREAD

**Issue by matthewford** [getsentry/raven-ruby#527]
Hello,

We're using https://github.com/heroku/rack-timeout

They seem to have rollbar support, where each timeout is grouped by URL, any ideas on how we could do something similar with sentry/raven?

**Comment by nateberkopec** [comment]
Would love to support it. We'd add something to the `integrations` folder.

**Comment by nateberkopec** [comment]
Coming soon to a release near you, or you can just drop #538 into your config/initializers to get it now.

**Comment by alex88** [comment]
I've upgraded to 2.0.1, configured sentry

```
Raven.configure do |config|
  config.dsn = 'https://xxx:xxx@sentry.io/xxx'
  config.environments = ['development', 'staging', 'production']
end
```

(notice I'm testing with development locally now) and logs shows raven is ready to catch error, then in a controller I've put a sleep to trigger the timeout and I get

```
source=rack-timeout id=dccc6823b700f7a210faf7eb23d21d82 timeout=5000ms service=1000ms state=active
source=rack-timeout id=dccc6823b700f7a210faf7eb23d21d82 timeout=5000ms service=2005ms state=active
source=rack-timeout id=dccc6823b700f7a210faf7eb23d21d82 timeout=5000ms service=3005ms state=active
source=rack-timeout id=dccc6823b700f7a210faf7eb23d21d82 timeout=5000ms service=4000ms state=active
source=rack-timeout id=dccc6823b700f7a210faf7eb23d21d82 timeout=5000ms service=5004ms state=active
source=rack-timeout id=dccc6823b700f7a210faf7eb23d21d82 timeout=5000ms service=5004ms state=timed_out
Completed 500 Internal Server Error in 4894ms (ActiveRecord: 0.0ms)

Rack::Timeout::RequestTimeoutException - Request ran for longer than 5000ms:
  app/controllers/pages_controller.rb:7:in `test'
  actionpack (4.1.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.13) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.13) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.13) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.13) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.13) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.13) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.13) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.13) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.13) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.13) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.13) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.13) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.13) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.13) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.13) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.13) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.13) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.13) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.13) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.13) lib/action_dispatch/routing/route_set.rb:692:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  lib/middleware/raw_parser_middleware.rb:12:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.13) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.13) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.13) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.13) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
  rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
  activesupport (4.1.13) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  sentry-raven (2.0.1) lib/raven/integrations/rack.rb:50:in `call'
  hirefire-resource (0.3.8) lib/hirefire/middleware.rb:38:in `call'
  railties (4.1.13) lib/rails/engine.rb:514:in `call'
  railties (4.1.13) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (2.14.0) lib/puma/server.rb:541:in `handle_request'
  puma (2.14.0) lib/puma/server.rb:388:in `process_client'
  puma (2.14.0) lib/puma/server.rb:270:in `block in run'
  puma (2.14.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

source=rack-timeout id=dccc6823b700f7a210faf7eb23d21d82 timeout=5000ms service=5008ms state=completed
```

but raven doesn't catch any error, any idea?
