### ISSUE TITLE
Raven crash: ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by dentarg** [getsentry/raven-ruby#653]
Our Sinatra app received requests like the one I'm using here, which triggered an exception in our app, but because of the exception in sentry-raven, that exception didn't reach Sentry, and the app crashed. Thankfully we had logs that could be used to discover the real issue in the application. :)  

Seems like there's a bug when the Rack integration is sanitizing data.

```
$ dotenv bundle exec ruby test.rb
I, [2017-03-24T16:18:03.263380 #95532]  INFO -- sentry: ** [Raven] Raven 2.4.0 ready to catch errors
Loaded suite test
Started
I, [2017-03-24T16:18:03.324465 #95532]  INFO -- sentry: ** [Raven] Sending event 59ae5001edde4bb49b49cfe3ead68291 to Sentry
E
=====================================================================================================================================================================================
Error: test_ok(HomepageTest): ArgumentError: invalid byte sequence in UTF-8
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:32:in `match'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:32:in `sanitize'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:26:in `block in sanitize'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:26:in `map'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:26:in `sanitize'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `block in process'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `each'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `each_with_object'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `process'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:49:in `sanitize_query_string'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:28:in `sanitize'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `block in process'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `each'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `each_with_object'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `process'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:24:in `sanitize'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `block in process'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `each'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `each_with_object'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/processor/sanitizedata.rb:19:in `process'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/client.rb:66:in `block in encode'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/client.rb:66:in `each'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/client.rb:66:in `reduce'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/client.rb:66:in `encode'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/client.rb:37:in `send_event'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/instance.rb:81:in `send_event'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/instance.rb:126:in `capture_type'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/integrations/rack.rb:28:in `capture_type'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/integrations/rack.rb:54:in `rescue in call'
/Users/dentarg/.gem/ruby/2.3.3/gems/sentry-raven-2.4.0/lib/raven/integrations/rack.rb:49:in `call'
/Users/dentarg/.gem/ruby/2.3.3/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
/Users/dentarg/.gem/ruby/2.3.3/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
/Users/dentarg/.gem/ruby/2.3.3/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
/Users/dentarg/.gem/ruby/2.3.3/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
test.rb:27:in `test_ok'
     24:   end
     25:
     26:   def test_ok
  => 27:     get "/?foo=bar%E9"
     28:     assert last_response.ok?
     29:   end
     30: end
```

Complete repro at https://github.com/dentarg/gists/tree/master/gists/sentry-raven-sanitize-13b5

**Comment by nateberkopec** [comment]
Thanks for the repro. This is weird, because the UTF8 processor should take care of this.

**Comment by rocketblr** [comment]
I can confirm that the same issue exists in my Rails application. Here is our app log:
I, [2017-04-11T20:46:10.832358 #19322]  INFO -- : Completed 500 Internal Server Error in 86ms (ActiveRecord: 5.6ms)
I, [2017-04-11T20:46:10.846057 #19322]  INFO -- : Sending event 91321e6d9acd4de6b30a7a09323ffced to Sentry
F, [2017-04-11T20:46:10.899170 #19322] FATAL -- : 
ArgumentError (invalid byte sequence in UTF-8):

Events with this exact error don't appear in Sentry dashboard. Others working well.

**Comment by jakeonfire** [comment]
You'll never believe this, @nateberkopec, but we're running into this issue where the `key` has an invalid encoding. E.g.:
```ruby
{
  "yadda-yadda" => "...",
  "query_string" => "ti3xhdmfos%c1%819u8lw5gtb9=1",
  "yadda-yadda" => "..."
}
```
which - on `CGI.parse` - becomes:
```ruby
{
  "ti3xhdmfos\xC1\x819u8lw5gtb9"=>["1"]
}
```
and the extra `utf8_processor.process` only operates on the values.

**Comment by jakeonfire** [comment]
I wanted to add that our app has no need for such data, so I'm not yet sure where it's coming from or why, but it does blow up with a similar stack trace to the above:
```
WARN: ArgumentError: invalid byte sequence in UTF-8
WARN: /usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:61:in `=~'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:61:in `matches_regexes?'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:32:in `process'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:25:in `block in process'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:25:in `map!'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:25:in `process'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:23:in `block in process'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:23:in `merge!'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:23:in `process'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:55:in `sanitize_query_string'
/usr/local/bundle/gems/sentry-raven-2.11.0/lib/raven/processor/sanitizedata.rb:35:in `process'
...
```
