### ISSUE TITLE
Document latest release instead of master

### ISSUE THREAD

**Issue by dentarg** [getsentry/raven-ruby#666]
The following isn't a great user experience at all, and makes you scratch your head for quite a bit. 

```
$ bundle init
Writing new Gemfile to /private/tmp/raven/Gemfile

$ echo "gem 'sentry-raven'" >> Gemfile

$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using multipart-post 2.0.0
Using bundler 1.14.6
Installing faraday 0.12.1
Installing sentry-raven 2.4.0
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Using snippet from https://docs.sentry.io/clients/ruby/config/

```ruby
$ cat app.rb
require "raven"

Raven.configure do |config|
  config.sanitize_data_for_request_methods = %w(PATCH) # Only send data for PATCH request method
  config.processors -= [Raven::Processor::RequestMethodData] # Do this to always send request data
  config.processors -= [Raven::Processor::Cookies] # Do this to send cookies by default
end
```

```
$ bundle exec ruby app.rb
app.rb:4:in `block in <main>': undefined method `sanitize_data_for_request_methods=' for #<Raven::Configuration:0x007f9af990b3e8> (NoMethodError)
	from /Users/dentarg/.gem/ruby/2.2.7/gems/sentry-raven-2.4.0/lib/raven/instance.rb:68:in `configure'
	from /Users/dentarg/.rubies/ruby-2.2.7/lib/ruby/2.2.0/forwardable.rb:204:in `configure'
	from app.rb:3:in `<main>'
```

**Comment by dentarg** [comment]
Do docs.sentry.io hold docs for specific versions? Would be great to be able to see the docs for 2.4.0.

**Comment by dentarg** [comment]
Not as pretty as https://docs.sentry.io/, but always something: https://github.com/getsentry/raven-ruby/blob/v2.4.0/docs/config.rst

**Comment by nateberkopec** [comment]
Opening this in the sentry-docs repo
