### ISSUE TITLE
Raven unable to capture RestClient exceptions?

### ISSUE THREAD

**Issue by AaronRustad** [getsentry/raven-ruby#695]
I've run across an interesting situation where Raven doesn't seem to be able to handle `RestClient::RequestTimeout`. 

Example, from the console:

```text
irb(main):011:0> Raven.capture { raise(RestClient::RequestTimeout, 'AaronTesting.') }
SystemStackError: stack level too deep
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:72:in `method_missing'
... 10034 levels...
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb:154:in `block (3 levels) in <module:RestClient>'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.5.2/lib/raven/event.rb:109:in `block in from_exception'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.5.2/lib/raven/event.rb:55:in `initialize'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.5.2/lib/raven/event.rb:107:in `new'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.5.2/lib/raven/event.rb:107:in `from_exception'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.5.2/lib/raven/instance.rb:114:in `capture_type'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.5.2/lib/raven/instance.rb:97:in `rescue in capture'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.5.2/lib/raven/instance.rb:92:in `capture'
        from (irb):11
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
irb(main):012:0>
```

And a regular error does seem to submit correctly:

```text
irb(main):012:0> Raven.capture { raise(StandardError, 'AaronTesting.') }
Sending event 8be9e7784b954cba82416999698fd4e2 to Sentry
StandardError: AaronTesting.
        from (irb):12:in `block in irb_binding'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.5.2/lib/raven/instance.rb:93:in `capture'
        from (irb):12
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /lift/data/www/rtopia/shared/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
irb(main):013:0>
```

As you can see, in Sentry, only the `StandardError` is recorded.

![liftopia___lifty](https://user-images.githubusercontent.com/17159/27044447-d4ca8156-4f5a-11e7-944f-8898b9a0de61.jpg)

Thanks for your help!
Aaron.

**Comment by nateberkopec** [comment]
This is a problem with RestClient, which looks like it's calling itself in a loop after we ask for the exception's `message`. I'd raise an issue over there.
