### ISSUE TITLE
"not opened for reading" error raised when trying to report errors coming from a Rack application

### ISSUE THREAD

**Issue by perlun** [getsentry/raven-ruby#721]
Here is an excerpt from the stack trace:

```
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger: Error message: not opened for reading
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger: Stack trace:
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.6.0/lib/raven/integrations/rack.rb:89:in `read'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.6.0/lib/raven/integrations/rack.rb:89:in `read_data_from'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.6.0/lib/raven/integrations/rack.rb:75:in `from_rack'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/uxfactory-server-8.3.0/src/server/lib/sentry/sentry.rb:29:in `block (2 levels) in capture_exception'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.6.0/lib/raven/interface.rb:8:in `initialize'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.6.0/lib/raven/interfaces/http.rb:11:in `initialize'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.6.0/lib/raven/event.rb:230:in `new'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.6.0/lib/raven/event.rb:230:in `interface'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/uxfactory-server-8.3.0/src/server/lib/sentry/sentry.rb:28:in `block in capture_exception'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.6.0/lib/raven/instance.rb:115:in `capture_type'
Jul 27 05:51:57 microservice-ruby24-appfactory-applications time-backend: ERROR ConsoleLogger:         /dist/uxfactoryserver/ecraft.uxfactory.time.dist/releases/44/vendor/bundle/ruby/2.4.0/gems/uxfactory-server-8.3.0/src/server/lib/sentry/sentry.rb:27:in `capture_exception'
```

Any ideas what could be causing this, or ideas about how I could debug it further?

**Comment by nateberkopec** [comment]
Interesting. What application server? Puma, Unicorn, etc?

**Comment by perlun** [comment]
Puma 3.9 in this case, with our own Sinatra-based application server on top of it.

**Comment by nateberkopec** [comment]
If the request body isn't opened for reading, it's probably something in your middleware stack or application server config. I can't think of anything in particular off the top of my head.

**Comment by nateberkopec** [comment]
Linking #366.

**Comment by nateberkopec** [comment]
@perlun I guess you're doing

```ruby
config.async = lambda { |event|
    Thread.new { Raven.send_event(event) }
  }
``` 

then?

**Comment by nateberkopec** [comment]
FWIW this has pretty much always been a problem, I just sort of ignored it in #366 but there's no workaround/downgrade option here. I think it may only be a problem if you're using `config.async` with `Thread.new { }`, but I'm not sure.

**Comment by nateberkopec** [comment]
I've decided to swallow IOErrors here for now. 

I was wrong about this being related to threading - the error above happens before the async callback is called. 

You have a middleware somewhere in your application which is reading the request body but not rewinding it. I don't have a lot of guidance here on how to *find* that particular middleware. I guess you could wrap some kind of listener around the Rack body and log whenever it's read. Might be easier to just remove middlewares until you find the one that causes the problem.
