### ISSUE TITLE
Can't send a range of time objects in additional context

### ISSUE THREAD

**Issue by daxhuiberts** [getsentry/raven-ruby#723]
I'm not sure if this is related to the ruby gem or the sentry server end-point, but as of a month ago or so I'm not able to do the following anymore:

```
Raven.capture_message('test', extra: {test: Time.parse('2017-01-01')..Time.parse('2017-01-30')})
```

I can send time objects (`Raven.capture_message('test', extra: {test: Time.parse('2017-01-01')}`) and a range of integers (`Raven.capture_message('test', extra: {test: 1..100}`), but not a combination of that.

I get the following stack trace:

```
Sending event 02b261fc208d47dbb6518deacd09bafc to Sentry
Raven HTTP Transport connecting to https://app.getsentry.com
Unable to record event with remote Sentry server (Raven::Error - the server responded with status 400 Error in headers is: Bad data reconstructing object (ValueError, Unexpected character in found when decoding object value)):
/data/salonized/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.6.0/lib/raven/transports/http.rb:35:in `rescue in send_event'
/data/salonized/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.6.0/lib/raven/transports/http.rb:18:in `send_event'
/data/salonized/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.6.0/lib/raven/client.rb:40:in `send_event'
/data/salonized/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.6.0/lib/raven/instance.rb:81:in `send_event'
/data/salonized/shared/bundle/ruby/2.3.0/gems/sentry-raven-2.6.0/lib/raven/instance.rb:126:in `capture_type'
/opt/rubies/ruby-2.3.4/lib/ruby/2.3.0/forwardable.rb:204:in `capture_message'
(pry):2:in `__pry__'
/data/salonized/shared/bundle/ruby/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
/data/salonized/shared/bundle/ruby/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/data/salonized/shared/bundle/ruby/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'
/data/salonized/shared/bundle/ruby/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
Failed to submit event: test
```

I'm running on version 2.6.0 of the gem.

**Comment by nateberkopec** [comment]
Hmm, the final output looks like:

```
\"test\":\"2017-01-01 00:00:00 -0700..2017-01-30 00:00:00 -0700\"
```

Integer looks like the same:

```
\"test\":\"1..30\"
```

It looks like the server is just interpreting these values as strings, but is maybe getting a little too clever when reconstructing them. I would open this issue on the Sentry server repository and link back here.
