### ISSUE TITLE
TLS error appears to keep raven-ruby from talking to sentry

### ISSUE THREAD

**Issue by xrl** [getsentry/raven-ruby#851]
We are shipping our rails app with a docker container, `FROM ruby:2.5.1`, `OpenSSL 1.1.0f  25 May 2017`, and sentry-raven version `2.7.2` and faraday `0.9.2`. We get this error in our logs:

```
Unable to record event with remote Sentry server (Raven::Error - SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello):
/usr/local/bundle/gems/sentry-raven-2.7.2/lib/raven/transports/http.rb:34:in `rescue in send_event'
/usr/local/bundle/gems/sentry-raven-2.7.2/lib/raven/transports/http.rb:16:in `send_event'
/usr/local/bundle/gems/sentry-raven-2.7.2/lib/raven/client.rb:37:in `send_event'
/usr/local/bundle/gems/sentry-raven-2.7.2/lib/raven/instance.rb:81:in `send_event'
```

We host Sentry in our kubernetes cluster and expose it through an nginx-ingress controller. The controller is running `OpenSSL 1.0.2k  26 Jan 2017`.

**Comment by xrl** [comment]
We restarted the sentry worker and that appears to have unblocked things. This openssl error may be unrelated.
