### ISSUE TITLE
Sentry integrations causes FrozenError in actionpack-5.2.0

### ISSUE THREAD

**Issue by marksiemers** [getsentry/raven-ruby#856]
```
Failure/Error: require File.expand_path('../config/environment', __dir__)

FrozenError:
  can't modify frozen Array
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/stack.rb:76:in `insert'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/stack.rb:76:in `insert'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/integrations/rails.rb:10:in `block in <class:Rails>'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
# /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
# ./config/environment.rb:5:in `<top (required)>'
```

ruby 2.5.1
rails 5.2.0

**Comment by zzet** [comment]
@marksiemers try to update your rails application completely. I've solved my problem by this gem: https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#bootsnap

**Comment by marksiemers** [comment]
Yeah, that seems to have done the trick. Thanks!
