### ISSUE TITLE
Error reporting silently fails if sanitize_fields is array of symbols

### ISSUE THREAD

**Issue by swrobel** [getsentry/raven-ruby#925]
In my config, I didn't call `.map(&:to_s)` on `Rails.application.config.filter_parameters` when setting `sanitize_fields`. This caused Sentry to seem like it was working, yet no events were appearing.

Example from logs:

```
INFO -- : Completed 500 Internal Server Error in 13ms
INFO -- : Sending event 3e2bd623c90c4548a00ae8b1d57e3501 to Sentry 
FATAL -- : NoMethodError (undefined method `type' for nil:NilClass):
...
```

I was finally able to diagnose by running `rake raven:test`

```
$ heroku run rake raven:test
I, [2019-10-02T02:51:04.898674 #4]  INFO -- sentry: ** [Raven] Raven 2.11.3 ready to catch errors
I, [2019-10-02T02:51:04.991889 #4]  INFO -- : Raven 2.11.3 ready to catch errors
-> Sending a test event:
-> 
-> Sending event 4f9824e2147a48d4ba7b02f518759960 to Sentry
-> Sending event 74144c0fef2a4ac9be90df3a57e85b23 to Sentry
bundler: failed to load command: rake (/app/vendor/bundle/ruby/2.6.0/bin/rake)
NoMethodError: undefined method `include?' for :password:Symbol
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:78:in `block in special_characters?'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:78:in `select'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:78:in `special_characters?'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:74:in `use_boundary?'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:69:in `block in fields_re'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:68:in `map'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:68:in `fields_re'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:29:in `process'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:23:in `block in process'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:23:in `merge!'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/processor/sanitizedata.rb:23:in `process'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/client.rb:71:in `block in encode'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/client.rb:71:in `each'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/client.rb:71:in `reduce'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/client.rb:71:in `encode'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/client.rb:40:in `send_event'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/instance.rb:81:in `send_event'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/instance.rb:126:in `capture_type'
  /app/vendor/ruby-2.6.4/lib/ruby/2.6.0/forwardable.rb:230:in `capture_exception'
  /app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.11.3/lib/raven/integrations/rake.rb:9:in `display_error_message'
  /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:195:in `rescue in standard_exception_handling'
  /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:185:in `standard_exception_handling'
  /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
  /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
  /app/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
  /app/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>'
```

**Comment by HazAT** [comment]
Thanks for reporting this, just to clarify, can you currently work around this bug or are you blocked on anything?

**Comment by swrobel** [comment]
I worked around it

**Comment by HazAT** [comment]
Ok, I am closing this then.
