### ISSUE TITLE
CI: RuboCop fails on 2.7

### ISSUE THREAD

**Issue by olleolleolle** [getsentry/raven-ruby#927]
**Problem**: ruby-head fails. Fails in linting.

**Background**

Very old RuboCop running: 0.41.2.

**Discussion**:

- Perhaps the CI job for RuboCop can be skipped for ruby-head?
- If it's not possible to update the RuboCop version, then perhaps the linting job can be run separately?

<details>

```
can't modify frozen String: "lint"

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/config.rb:102:in `capitalize!'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/config.rb:102:in `cop_enabled?'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/cop/team.rb:128:in `cop_enabled?'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/cop/team.rb:56:in `block in cops'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/cop/team.rb:56:in `select'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/cop/team.rb:56:in `cops'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/cop/team.rb:152:in `validate_config'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/cop/team.rb:35:in `initialize'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:211:in `new'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:211:in `inspect_file'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:182:in `block in do_inspection_loop'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:172:in `loop'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:172:in `do_inspection_loop'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:87:in `process_file'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:59:in `block in inspect_files'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:57:in `each'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:57:in `inspect_files'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/runner.rb:35:in `run'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/cli.rb:72:in `execute_runner'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/cli.rb:28:in `run'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/rake_task.rb:49:in `run_cli'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/rake_task.rb:37:in `run_main_task'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/rake_task.rb:29:in `block (2 levels) in initialize'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rake-13.0.0/lib/rake/file_utils_ext.rb:58:in `verbose'

/home/travis/build/getsentry/raven-ruby/vendor/bundle/ruby/2.7.0/gems/rubocop-0.41.2/lib/rubocop/rake_task.rb:27:in `block in initialize'
```

</details>

**Comment by st0012** [comment]
Thanks for reporting! 

The CI now runs green against [ruby-head](https://travis-ci.org/github/getsentry/raven-ruby/jobs/715416100) or [Ruby 2.7](https://travis-ci.org/github/getsentry/raven-ruby/jobs/715416095). I will also update the rubocop version & rules in the near future 😄
